apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-jxaz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pgad-tenant/status-quarkus-io/statusquarkusio-jxaz@sha256:b9d3647eec9b853efe8eba253e8ee3343fb4812b870d24e97158881d1028f4b5
        name: my-java-quarkus
        resources: {}
status: {}
